version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/auth:/etc/nginx/auth:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    environment:
      - NGINX_MAX_BODY_SIZE=200M
      - NGINX_ERROR_LOG_LEVEL=debug
    networks:
      - proxy
    restart: always
    
  gtm-server:
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    container_name: gtm_server
    environment:
      - PORT=8080
    networks:
      - proxy
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx/auth:/etc/nginx/auth:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=martin@frenchease.fr
    depends_on:
      - nginx-proxy
    networks:
      - proxy
    restart: always

networks:
  proxy:
    name: nginx-proxy

volumes:
  nginx-auth:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx/auth
  acme: